version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deokhugam-app
    env_file:
      - .env
    ports:
      - "${HOST_APP_PORT}:${CONTAINER_APP_PORT}"
    environment:
      POSTGRES_DB : ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_PORT: ${PG_PORT}

      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      HOST_APP_PORT: ${HOST_APP_PORT}
      CONTAINER_APP_PORT: ${CONTAINER_APP_PORT}

      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BASE_URL: ${AWS_S3_BASE_URL}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}

      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_SECRET_KEY: ${NAVER_SECRET_KEY}
      TESSDATA_PREFIX: ${TESSDATA_PREFIX}
    depends_on:
      - postgres
    networks:
      - deokhugam-network

  postgres:
    image: postgres:15
    container_name: deokhugam-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - deokhugam-network

volumes:
  postgres-data:

networks:
  deokhugam-network:
    driver: bridge