version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deokhugam-app
    env_file:
      - .env
    ports:
      - "${HOST_APP_PORT}:${CONTAINER_APP_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - postgres
    networks:
      - deokhugam-network

  postgres:
    image: postgres:15
    container_name: deokhugam-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - deokhugam-network

volumes:
  postgres-data:

networks:
  deokhugam-network:
    driver: bridge