spring:
  application:
    name: deokhugam
  config:
    import: optional:file:.env[.properties]  # .env import
  profiles:
    active: dev

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  batch:
    jdbc:
      initialize-schema: never

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: org.postgresql.Driver

# Swagger
springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    com.part3.deokhugam: DEBUG

ocr:
  traineddata: ${TESSDATA_PREFIX}

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_SECRET_KEY}

aws:
  accessKeyId: ${AWS_S3_ACCESS_KEY}
  secretKey: ${AWS_S3_SECRET_KEY}
  region: ${AWS_S3_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}
    base-url: ${AWS_S3_BASE_URL}

scheduler:
  batch:
    start-time: "0 55 9 * * *"