spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deokhugam
    username: deokhugam_user
    password: deokhugam1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com.part3.deokhugam: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.batch: DEBUG